channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pigz=2.6
  - bbmap=39.01
  - sortmerna=2.1b
  - samtools>=1.13
  - vsearch=2.22.1
  - bedtools=2.30.0
  - mafft=7.520
  - spades=3.15.5
